ignore:
  - "**/entity/**"
  - "**/aop/**"
  - "**/jasper/**"
  - "**/configs/**"
  - "**/demodata/**"
  - "**/exception/**"
  - "**/job/FlushingDataJob**"
  - "**/core/analyzer/auto/client/model/**"
  - "**/core/analyzer/auto/impl/SuggestedItem**"
  - "**/core/item/impl/provider/impl/mock/**"