FROM openjdk:8-jre

LABEL maintainer="Andrei Varabyeu <andrei_varabyeu@epam.com>"
LABEL version="@version@"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"

RUN apt-get update && \
    apt-get install -y fonts-noto && \
    rm -rf /var/lib/apt/lists/*

VOLUME /tmp
ADD build/libs/service-api-3.1.1-SNAPSHOT.jar app.jar

RUN sh -c 'touch /app.jar'
EXPOSE 8080

RUN sh -c "echo '#!/bin/bash \n\
exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar' > /run.sh"

RUN chmod +x /run.sh
RUN cat /run.sh

ENTRYPOINT ["/run.sh"]

