# syntax=docker/dockerfile:1.4
FROM --platform=$BUILDPLATFORM gradle:8.10.0-jdk21-alpine AS build
ARG RELEASE_MODE
ARG APP_VERSION
ARG BUILDKIT_INLINE_CACHE=1

WORKDIR /usr/app

COPY build.gradle settings.gradle gradle.properties project-properties.gradle ./
COPY gradle/wrapper ./gradle/wrapper

COPY api-registry/build.gradle api-registry/settings.gradle ./api-registry/

RUN --mount=type=cache,target=/root/.gradle/caches \
    --mount=type=cache,target=/root/.gradle/wrapper \
    gradle dependencies --no-daemon || true

COPY src ./src
COPY api-registry ./api-registry

RUN --mount=type=cache,target=/root/.gradle/caches \
    --mount=type=cache,target=/root/.gradle/wrapper \
    if [ "${RELEASE_MODE}" = "true" ]; then \
        gradle build --parallel --build-cache --exclude-task test \
            -PreleaseMode=true \
            -Dorg.gradle.project.version=${APP_VERSION} \
            -Dorg.gradle.caching=true; \
    else \
        gradle build --parallel --build-cache --exclude-task test \
            -Dorg.gradle.project.version=${APP_VERSION} \
            -Dorg.gradle.caching=true; \
    fi

FROM amazoncorretto:21.0.9
LABEL version=${APP_VERSION} description="EPAM Report portal. Main API Service" maintainer="Andrei Varabyeu <andrei_varabyeu@epam.com>, Hleb Kanonik <hleb_kanonik@epam.com>"
ARG APP_VERSION=${APP_VERSION}
ENV APP_DIR=/usr/app
ENV JAVA_OPTS="-Xmx1g -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=70 -Djava.security.egd=file:/dev/./urandom "
WORKDIR $APP_DIR
COPY --from=build $APP_DIR/build/libs/service-api-*exec.jar .
VOLUME ["/tmp"]
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar ${APP_DIR}/service-api-*exec.jar"]
