/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.infrastructure.persistence.jooq.enums;


import com.epam.reportportal.infrastructure.persistence.jooq.JPublic;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public enum JIntegrationGroupEnum implements EnumType {

  BTS("BTS"),

  NOTIFICATION("NOTIFICATION"),

  AUTH("AUTH"),

  OTHER("OTHER"),

  IMPORT("IMPORT");

  private final String literal;

  private JIntegrationGroupEnum(String literal) {
    this.literal = literal;
  }

  @Override
  public Catalog getCatalog() {
    return getSchema().getCatalog();
  }

  @Override
  public Schema getSchema() {
    return JPublic.PUBLIC;
  }

  @Override
  public String getName() {
    return "integration_group_enum";
  }

  @Override
  public String getLiteral() {
    return literal;
  }

  /**
   * Lookup a value of this EnumType by its literal. Returns
   * <code>null</code>, if no such value could be found, see {@link
   * EnumType#lookupLiteral(Class, String)}.
   */
  public static JIntegrationGroupEnum lookupLiteral(String literal) {
    return EnumType.lookupLiteral(JIntegrationGroupEnum.class, literal);
  }
}
