/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.infrastructure.persistence.jooq.tables.JItemAttribute;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JItemAttributeRecord extends UpdatableRecordImpl<JItemAttributeRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.item_attribute.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.item_attribute.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.item_attribute.key</code>.
   */
  public void setKey(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.item_attribute.key</code>.
   */
  public String getKey() {
    return (String) get(1);
  }

  /**
   * Setter for <code>public.item_attribute.value</code>.
   */
  public void setValue(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.item_attribute.value</code>.
   */
  public String getValue() {
    return (String) get(2);
  }

  /**
   * Setter for <code>public.item_attribute.item_id</code>.
   */
  public void setItemId(Long value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.item_attribute.item_id</code>.
   */
  public Long getItemId() {
    return (Long) get(3);
  }

  /**
   * Setter for <code>public.item_attribute.launch_id</code>.
   */
  public void setLaunchId(Long value) {
    set(4, value);
  }

  /**
   * Getter for <code>public.item_attribute.launch_id</code>.
   */
  public Long getLaunchId() {
    return (Long) get(4);
  }

  /**
   * Setter for <code>public.item_attribute.system</code>.
   */
  public void setSystem(Boolean value) {
    set(5, value);
  }

  /**
   * Getter for <code>public.item_attribute.system</code>.
   */
  public Boolean getSystem() {
    return (Boolean) get(5);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JItemAttributeRecord
   */
  public JItemAttributeRecord() {
    super(JItemAttribute.ITEM_ATTRIBUTE);
  }

  /**
   * Create a detached, initialised JItemAttributeRecord
   */
  public JItemAttributeRecord(Long id, String key, String value, Long itemId, Long launchId, Boolean system) {
    super(JItemAttribute.ITEM_ATTRIBUTE);

    setId(id);
    setKey(key);
    setValue(value);
    setItemId(itemId);
    setLaunchId(launchId);
    setSystem(system);
    resetChangedOnNotNull();
  }
}
