/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.infrastructure.persistence.jooq.tables.JTmsTestCaseExecution;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsTestCaseExecutionRecord extends UpdatableRecordImpl<JTmsTestCaseExecutionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_test_case_execution.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_test_case_execution.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_test_case_execution.test_item_id</code>.
     */
    public void setTestItemId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_test_case_execution.test_item_id</code>.
     */
    public Long getTestItemId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.tms_test_case_execution.test_case_id</code>.
     */
    public void setTestCaseId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_test_case_execution.test_case_id</code>.
     */
    public Long getTestCaseId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.tms_test_case_execution.launch_id</code>.
     */
    public void setLaunchId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tms_test_case_execution.launch_id</code>.
     */
    public Long getLaunchId() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>public.tms_test_case_execution.test_case_version_id</code>.
     */
    public void setTestCaseVersionId(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.tms_test_case_execution.test_case_version_id</code>.
     */
    public Long getTestCaseVersionId() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>public.tms_test_case_execution.test_case_snapshot</code>.
     */
    public void setTestCaseSnapshot(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.tms_test_case_execution.test_case_snapshot</code>.
     */
    public JSONB getTestCaseSnapshot() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsTestCaseExecutionRecord
     */
    public JTmsTestCaseExecutionRecord() {
        super(JTmsTestCaseExecution.TMS_TEST_CASE_EXECUTION);
    }

    /**
     * Create a detached, initialised JTmsTestCaseExecutionRecord
     */
    public JTmsTestCaseExecutionRecord(Long id, Long testItemId, Long testCaseId, Long launchId, Long testCaseVersionId, JSONB testCaseSnapshot) {
        super(JTmsTestCaseExecution.TMS_TEST_CASE_EXECUTION);

        setId(id);
        setTestItemId(testItemId);
        setTestCaseId(testCaseId);
        setLaunchId(launchId);
        setTestCaseVersionId(testCaseVersionId);
        setTestCaseSnapshot(testCaseSnapshot);
        resetChangedOnNotNull();
    }
}
