/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JAttribute;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JAttributeRecord extends UpdatableRecordImpl<JAttributeRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.attribute.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.attribute.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.attribute.name</code>.
   */
  public void setName(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.attribute.name</code>.
   */
  public String getName() {
    return (String) get(1);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JAttributeRecord
   */
  public JAttributeRecord() {
    super(JAttribute.ATTRIBUTE);
  }

  /**
   * Create a detached, initialised JAttributeRecord
   */
  public JAttributeRecord(Long id, String name) {
    super(JAttribute.ATTRIBUTE);

    setId(id);
    setName(name);
    resetChangedOnNotNull();
  }
}
