/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.base.infrastructure.persistence.jooq.enums.JLogicalOperatorEnum;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JSenderCase;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JSenderCaseRecord extends UpdatableRecordImpl<JSenderCaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sender_case.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sender_case.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sender_case.send_case</code>.
     */
    public void setSendCase(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sender_case.send_case</code>.
     */
    public String getSendCase() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.sender_case.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sender_case.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.sender_case.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sender_case.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.sender_case.attributes_operator</code>.
     */
    public void setAttributesOperator(JLogicalOperatorEnum value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sender_case.attributes_operator</code>.
     */
    public JLogicalOperatorEnum getAttributesOperator() {
        return (JLogicalOperatorEnum) get(4);
    }

    /**
     * Setter for <code>public.sender_case.rule_name</code>.
     */
    public void setRuleName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.sender_case.rule_name</code>.
     */
    public String getRuleName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.sender_case.rule_type</code>.
     */
    public void setRuleType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.sender_case.rule_type</code>.
     */
    public String getRuleType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.sender_case.rule_details</code>.
     */
    public void setRuleDetails(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.sender_case.rule_details</code>.
     */
    public JSONB getRuleDetails() {
        return (JSONB) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JSenderCaseRecord
     */
    public JSenderCaseRecord() {
        super(JSenderCase.SENDER_CASE);
    }

    /**
     * Create a detached, initialised JSenderCaseRecord
     */
    public JSenderCaseRecord(Long id, String sendCase, Long projectId, Boolean enabled, JLogicalOperatorEnum attributesOperator, String ruleName, String ruleType, JSONB ruleDetails) {
        super(JSenderCase.SENDER_CASE);

        setId(id);
        setSendCase(sendCase);
        setProjectId(projectId);
        setEnabled(enabled);
        setAttributesOperator(attributesOperator);
        setRuleName(ruleName);
        setRuleType(ruleType);
        setRuleDetails(ruleDetails);
        resetChangedOnNotNull();
    }
}
