/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsTextManualScenarioAttachment;

import java.time.Instant;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsTextManualScenarioAttachmentRecord extends UpdatableRecordImpl<JTmsTextManualScenarioAttachmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.tms_text_manual_scenario_attachment.text_manual_scenario_id</code>.
     */
    public void setTextManualScenarioId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.tms_text_manual_scenario_attachment.text_manual_scenario_id</code>.
     */
    public Long getTextManualScenarioId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.tms_text_manual_scenario_attachment.attachment_id</code>.
     */
    public void setAttachmentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.tms_text_manual_scenario_attachment.attachment_id</code>.
     */
    public Long getAttachmentId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>public.tms_text_manual_scenario_attachment.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.tms_text_manual_scenario_attachment.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsTextManualScenarioAttachmentRecord
     */
    public JTmsTextManualScenarioAttachmentRecord() {
        super(JTmsTextManualScenarioAttachment.TMS_TEXT_MANUAL_SCENARIO_ATTACHMENT);
    }

    /**
     * Create a detached, initialised JTmsTextManualScenarioAttachmentRecord
     */
    public JTmsTextManualScenarioAttachmentRecord(Long textManualScenarioId, Long attachmentId, Instant createdAt) {
        super(JTmsTextManualScenarioAttachment.TMS_TEXT_MANUAL_SCENARIO_ATTACHMENT);

        setTextManualScenarioId(textManualScenarioId);
        setAttachmentId(attachmentId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
