/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsDataset;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsDatasetRecord extends UpdatableRecordImpl<JTmsDatasetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_dataset.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_dataset.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_dataset.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_dataset.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tms_dataset.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_dataset.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsDatasetRecord
     */
    public JTmsDatasetRecord() {
        super(JTmsDataset.TMS_DATASET);
    }

    /**
     * Create a detached, initialised JTmsDatasetRecord
     */
    public JTmsDatasetRecord(Long id, String name, Long projectId) {
        super(JTmsDataset.TMS_DATASET);

        setId(id);
        setName(name);
        setProjectId(projectId);
        resetChangedOnNotNull();
    }
}
