/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsTestPlanTestCase;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsTestPlanTestCaseRecord extends UpdatableRecordImpl<JTmsTestPlanTestCaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_test_plan_test_case.test_plan_id</code>.
     */
    public void setTestPlanId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_test_plan_test_case.test_plan_id</code>.
     */
    public Long getTestPlanId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_test_plan_test_case.test_case_id</code>.
     */
    public void setTestCaseId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_test_plan_test_case.test_case_id</code>.
     */
    public Long getTestCaseId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsTestPlanTestCaseRecord
     */
    public JTmsTestPlanTestCaseRecord() {
        super(JTmsTestPlanTestCase.TMS_TEST_PLAN_TEST_CASE);
    }

    /**
     * Create a detached, initialised JTmsTestPlanTestCaseRecord
     */
    public JTmsTestPlanTestCaseRecord(Long testPlanId, Long testCaseId) {
        super(JTmsTestPlanTestCase.TMS_TEST_PLAN_TEST_CASE);

        setTestPlanId(testPlanId);
        setTestCaseId(testCaseId);
        resetChangedOnNotNull();
    }
}
