/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.base.infrastructure.persistence.jooq.enums.JTmsDatasetType;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsEnvironmentDataset;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsEnvironmentDatasetRecord extends UpdatableRecordImpl<JTmsEnvironmentDatasetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_environment_dataset.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_environment_dataset.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_environment_dataset.environment_id</code>.
     */
    public void setEnvironmentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_environment_dataset.environment_id</code>.
     */
    public Long getEnvironmentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.tms_environment_dataset.dataset_id</code>.
     */
    public void setDatasetId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_environment_dataset.dataset_id</code>.
     */
    public Long getDatasetId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.tms_environment_dataset.dataset_type</code>.
     */
    public void setDatasetType(JTmsDatasetType value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tms_environment_dataset.dataset_type</code>.
     */
    public JTmsDatasetType getDatasetType() {
        return (JTmsDatasetType) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsEnvironmentDatasetRecord
     */
    public JTmsEnvironmentDatasetRecord() {
        super(JTmsEnvironmentDataset.TMS_ENVIRONMENT_DATASET);
    }

    /**
     * Create a detached, initialised JTmsEnvironmentDatasetRecord
     */
    public JTmsEnvironmentDatasetRecord(Long id, Long environmentId, Long datasetId, JTmsDatasetType datasetType) {
        super(JTmsEnvironmentDataset.TMS_ENVIRONMENT_DATASET);

        setId(id);
        setEnvironmentId(environmentId);
        setDatasetId(datasetId);
        setDatasetType(datasetType);
        resetChangedOnNotNull();
    }
}
