/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsEnvironment;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsEnvironmentRecord extends UpdatableRecordImpl<JTmsEnvironmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_environment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_environment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_environment.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_environment.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tms_environment.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_environment.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsEnvironmentRecord
     */
    public JTmsEnvironmentRecord() {
        super(JTmsEnvironment.TMS_ENVIRONMENT);
    }

    /**
     * Create a detached, initialised JTmsEnvironmentRecord
     */
    public JTmsEnvironmentRecord(Long id, String name, Long projectId) {
        super(JTmsEnvironment.TMS_ENVIRONMENT);

        setId(id);
        setName(name);
        setProjectId(projectId);
        resetChangedOnNotNull();
    }
}
