FROM gradle:jdk10-slim as builder

COPY --chown=gradle:gradle . /home/gradle/
WORKDIR /home/gradle
RUN gradle build

FROM openjdk:8-jre-slim

LABEL maintainer="Andrei Varabyeu <andrei_varabyeu@epam.com>"
LABEL version="@version@"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
ENV JAVA_APP=/app.jar

RUN apt-get update && \
    apt-get install -y fonts-noto net-tools && \
    rm -rf /var/lib/apt/lists/*

RUN sh -c "echo '#!/bin/sh \n\
exec java $JAVA_OPTS -jar $JAVA_APP' > /start.sh && chmod +x /start.sh"

VOLUME /tmp

RUN mkdir plugins

COPY --from=builder /home/gradle/build/libs/service-api.jar ./app.jar

RUN sh -c 'touch /app.jar'

EXPOSE 8080

ENTRYPOINT /start.sh