FROM openjdk:8-jre-alpine

MAINTAINER Andrei Varabyeu <andrei_varabyeu@epam.com>
LABEL version="@version@"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx1g"

RUN apk --no-cache add ttf-droid

VOLUME /tmp
ADD @name@-@version@.jar app.jar

RUN sh -c 'touch /app.jar'
EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -jar /app.jar"]

