FROM adoptopenjdk:11-jdk-hotspot-bionic as builder

RUN apt-get update && apt-get install ca-certificates git fonts-noto zip -y

RUN addgroup -system --gid 1000 rp-builder
RUN adduser --disabled-password --system --ingroup rp-builder --uid 1000 --shell /bin/bash rp-builder

USER rp-builder
WORKDIR /home/rp-builder

### Copy gradle wrapper's stuff to init and cache gradle wrapper
COPY --chown=rp-builder gradle/ ./gradle/
COPY --chown=rp-builder gradlew*  ./
RUN ./gradlew wrapper

ARG buildNumber
ARG sealightsSession
ARG sealightsToken

### Copy gradle build files to resolve and cache dependencies
COPY --chown=rp-builder *.gradle gradle.properties ./
RUN ./gradlew resolveDependencies -P sealightsToken=${sealightsToken} --stacktrace

### Copy source and run build
COPY --chown=rp-builder src/ ./src/
COPY --chown=rp-builder .git/ .git/

RUN ./gradlew build -x jacocoTestReport -P gcp -P buildNumber=${buildNumber} -P sealightsToken=${sealightsToken} -P sealightsSession=${sealightsSession} --full-stacktrace

RUN mkdir -p /home/rp-builder/plugins && \
    wget -O /home/rp-builder/plugins/sealights.zip https://agents.sealights.co/sealights-java/sealights-java-latest.zip && \
    unzip /home/rp-builder/plugins/sealights.zip -d /home/rp-builder/plugins && \
    mkdir -p /home/rp-builder/sealights && \
    sh -c "echo '${sealightsToken}' > /home/rp-builder/sealights/sealights-token.txt" && \
    sh -c "echo '${sealightsSession}' > /home/rp-builder/sealights/sealights-session.txt"

FROM openjdk:11-jre-slim

ARG version

### Set quay.io image cache. Since the build is for development only,
### there is no need to keep them forever
### details: https://support.coreos.com/hc/en-us/articles/115001384693-Tag-Expiration
LABEL quay.expires-after=1w

LABEL maintainer="Andrei Varabyeu <andrei_varabyeu@epam.com>"
LABEL version=${version}
LABEL description="ReportPortal API Service: Development Version"

ENV JAVA_OPTS="-DLOG_FILE=app.log -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
ENV JAVA_APP=/app/app.jar

RUN apt-get update && \
    apt-get install fonts-noto-core -y

RUN sh -c "echo $'#!/bin/sh \n\
exec java \$JAVA_OPTS -jar \$JAVA_APP' > /start.sh && chmod +x /start.sh"

VOLUME /tmp

RUN mkdir plugins app
COPY --from=builder /home/rp-builder/plugins/sl-test-listener.jar ./plugins/
COPY --from=builder /home/rp-builder/sealights/sealights-token.txt /home/rp-builder/sealights/sealights-session.txt ./

COPY --from=builder /home/rp-builder/build/libs/app.jar /app/

RUN sh -c "touch $JAVA_APP"

EXPOSE 8080
ENTRYPOINT /start.sh
