FROM openjdk:8-alpine

RUN apk add --no-cache ca-certificates git curl font-noto

RUN addgroup -S -g 1000 rp-builder
RUN adduser -D -S -G rp-builder -u 1000 -s /bin/ash rp-builder

USER rp-builder
WORKDIR /home/rp-builder

### Copy gradle wrapper's stuff to init and cache gradle wrapper
COPY --chown=rp-builder gradle/ ./gradle/
COPY --chown=rp-builder gradlew*  ./
RUN ./gradlew wrapper

### Copy gradle build files to resolve and cache dependencies
COPY --chown=rp-builder *.gradle gradle.properties ./
RUN ./gradlew resolveDependencies --stacktrace

### Copy source and run build
COPY --chown=rp-builder src/ ./src/
COPY --chown=rp-builder .git/ .git/
RUN ./gradlew build