FROM frolvlad/alpine-oraclejdk8:slim

MAINTAINER Andrei Varabyeu <andrei_varabyeu@epam.com>

RUN apk --no-cache add ttf-droid

VOLUME /tmp
ADD ${project.name}-${version}.jar app.jar
ADD jacocoagent.jar jacocoagent.jar

RUN sh -c 'touch /app.jar'
RUN sh -c 'touch /jacocoagent.jar'

EXPOSE 8080

ENTRYPOINT ["java","-Xmx1g","-Djava.security.egd=file:/dev/./urandom", "-javaagent:/jacocoagent.jar=destfile=/jacoco/jacoco.exec,append=false", "-jar","/app.jar"]
