FROM adoptopenjdk:11-jdk-hotspot-bionic

RUN apt-get update && \
    apt-get install fonts-noto-core -y

RUN addgroup -system --gid 1000 rp-builder
RUN adduser --disabled-password --system --ingroup rp-builder --uid 1000 --shell /bin/bash rp-builder

USER rp-builder
WORKDIR /home/rp-builder

### Copy gradle wrapper's stuff to init and cache gradle wrapper
COPY --chown=rp-builder gradle/ ./gradle/
COPY --chown=rp-builder gradlew*  ./
RUN ./gradlew wrapper

### Copy gradle build files to resolve and cache dependencies
COPY --chown=rp-builder *.gradle gradle.properties ./
RUN ./gradlew resolveDependencies --stacktrace

### Copy source and run build
COPY --chown=rp-builder src/ ./src/
COPY --chown=rp-builder .git/ .git/
RUN ./gradlew build