/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.pojos;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDashboardWidget implements Serializable {

	private static final long serialVersionUID = 1345997428;

	private Integer dashboardId;
	private Integer widgetId;
	private String widgetName;
	private Integer wdigetWidth;
	private Integer widgetHeigth;
	private Integer widgetPositionX;
	private Integer widgetPositionY;

	public JDashboardWidget() {
	}

	public JDashboardWidget(JDashboardWidget value) {
		this.dashboardId = value.dashboardId;
		this.widgetId = value.widgetId;
		this.widgetName = value.widgetName;
		this.wdigetWidth = value.wdigetWidth;
		this.widgetHeigth = value.widgetHeigth;
		this.widgetPositionX = value.widgetPositionX;
		this.widgetPositionY = value.widgetPositionY;
	}

	public JDashboardWidget(Integer dashboardId, Integer widgetId, String widgetName, Integer wdigetWidth, Integer widgetHeigth,
			Integer widgetPositionX, Integer widgetPositionY) {
		this.dashboardId = dashboardId;
		this.widgetId = widgetId;
		this.widgetName = widgetName;
		this.wdigetWidth = wdigetWidth;
		this.widgetHeigth = widgetHeigth;
		this.widgetPositionX = widgetPositionX;
		this.widgetPositionY = widgetPositionY;
	}

	public Integer getDashboardId() {
		return this.dashboardId;
	}

	public void setDashboardId(Integer dashboardId) {
		this.dashboardId = dashboardId;
	}

	public Integer getWidgetId() {
		return this.widgetId;
	}

	public void setWidgetId(Integer widgetId) {
		this.widgetId = widgetId;
	}

	public String getWidgetName() {
		return this.widgetName;
	}

	public void setWidgetName(String widgetName) {
		this.widgetName = widgetName;
	}

	public Integer getWdigetWidth() {
		return this.wdigetWidth;
	}

	public void setWdigetWidth(Integer wdigetWidth) {
		this.wdigetWidth = wdigetWidth;
	}

	public Integer getWidgetHeigth() {
		return this.widgetHeigth;
	}

	public void setWidgetHeigth(Integer widgetHeigth) {
		this.widgetHeigth = widgetHeigth;
	}

	public Integer getWidgetPositionX() {
		return this.widgetPositionX;
	}

	public void setWidgetPositionX(Integer widgetPositionX) {
		this.widgetPositionX = widgetPositionX;
	}

	public Integer getWidgetPositionY() {
		return this.widgetPositionY;
	}

	public void setWidgetPositionY(Integer widgetPositionY) {
		this.widgetPositionY = widgetPositionY;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JDashboardWidget (");

		sb.append(dashboardId);
		sb.append(", ").append(widgetId);
		sb.append(", ").append(widgetName);
		sb.append(", ").append(wdigetWidth);
		sb.append(", ").append(widgetHeigth);
		sb.append(", ").append(widgetPositionX);
		sb.append(", ").append(widgetPositionY);

		sb.append(")");
		return sb.toString();
	}
}
