/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.pojos;

import javax.annotation.Generated;
import java.io.Serializable;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.4" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIssue implements Serializable {

	private static final long serialVersionUID = 132964181;

	private Long issueId;
	private Integer issueType;
	private String issueDescription;
	private Boolean autoAnalyzed;
	private Boolean ignoreAnalyzer;

	public JIssue() {
	}

	public JIssue(JIssue value) {
		this.issueId = value.issueId;
		this.issueType = value.issueType;
		this.issueDescription = value.issueDescription;
		this.autoAnalyzed = value.autoAnalyzed;
		this.ignoreAnalyzer = value.ignoreAnalyzer;
	}

	public JIssue(Long issueId, Integer issueType, String issueDescription, Boolean autoAnalyzed, Boolean ignoreAnalyzer) {
		this.issueId = issueId;
		this.issueType = issueType;
		this.issueDescription = issueDescription;
		this.autoAnalyzed = autoAnalyzed;
		this.ignoreAnalyzer = ignoreAnalyzer;
	}

	public Long getIssueId() {
		return this.issueId;
	}

	public void setIssueId(Long issueId) {
		this.issueId = issueId;
	}

	public Integer getIssueType() {
		return this.issueType;
	}

	public void setIssueType(Integer issueType) {
		this.issueType = issueType;
	}

	public String getIssueDescription() {
		return this.issueDescription;
	}

	public void setIssueDescription(String issueDescription) {
		this.issueDescription = issueDescription;
	}

	public Boolean getAutoAnalyzed() {
		return this.autoAnalyzed;
	}

	public void setAutoAnalyzed(Boolean autoAnalyzed) {
		this.autoAnalyzed = autoAnalyzed;
	}

	public Boolean getIgnoreAnalyzer() {
		return this.ignoreAnalyzer;
	}

	public void setIgnoreAnalyzer(Boolean ignoreAnalyzer) {
		this.ignoreAnalyzer = ignoreAnalyzer;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JIssue (");

		sb.append(issueId);
		sb.append(", ").append(issueType);
		sb.append(", ").append(issueDescription);
		sb.append(", ").append(autoAnalyzed);
		sb.append(", ").append(ignoreAnalyzer);

		sb.append(")");
		return sb.toString();
	}
}
