/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.pojos;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIssue implements Serializable {

	private static final long serialVersionUID = 1021408965;

	private Long id;
	private Integer issueType;
	private String issueDescription;
	private Boolean autoAnalyzed;
	private Boolean ignoreAnalyzer;
	private Long testItemResultsId;

	public JIssue() {
	}

	public JIssue(JIssue value) {
		this.id = value.id;
		this.issueType = value.issueType;
		this.issueDescription = value.issueDescription;
		this.autoAnalyzed = value.autoAnalyzed;
		this.ignoreAnalyzer = value.ignoreAnalyzer;
		this.testItemResultsId = value.testItemResultsId;
	}

	public JIssue(Long id, Integer issueType, String issueDescription, Boolean autoAnalyzed, Boolean ignoreAnalyzer,
			Long testItemResultsId) {
		this.id = id;
		this.issueType = issueType;
		this.issueDescription = issueDescription;
		this.autoAnalyzed = autoAnalyzed;
		this.ignoreAnalyzer = ignoreAnalyzer;
		this.testItemResultsId = testItemResultsId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getIssueType() {
		return this.issueType;
	}

	public void setIssueType(Integer issueType) {
		this.issueType = issueType;
	}

	public String getIssueDescription() {
		return this.issueDescription;
	}

	public void setIssueDescription(String issueDescription) {
		this.issueDescription = issueDescription;
	}

	public Boolean getAutoAnalyzed() {
		return this.autoAnalyzed;
	}

	public void setAutoAnalyzed(Boolean autoAnalyzed) {
		this.autoAnalyzed = autoAnalyzed;
	}

	public Boolean getIgnoreAnalyzer() {
		return this.ignoreAnalyzer;
	}

	public void setIgnoreAnalyzer(Boolean ignoreAnalyzer) {
		this.ignoreAnalyzer = ignoreAnalyzer;
	}

	public Long getTestItemResultsId() {
		return this.testItemResultsId;
	}

	public void setTestItemResultsId(Long testItemResultsId) {
		this.testItemResultsId = testItemResultsId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JIssue (");

		sb.append(id);
		sb.append(", ").append(issueType);
		sb.append(", ").append(issueDescription);
		sb.append(", ").append(autoAnalyzed);
		sb.append(", ").append(ignoreAnalyzer);
		sb.append(", ").append(testItemResultsId);

		sb.append(")");
		return sb.toString();
	}
}
