/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.pojos;

import javax.annotation.Generated;
import java.io.Serializable;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.4" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIssueTicket implements Serializable {

	private static final long serialVersionUID = 57493091;

	private Long issueId;
	private Long ticketId;

	public JIssueTicket() {
	}

	public JIssueTicket(JIssueTicket value) {
		this.issueId = value.issueId;
		this.ticketId = value.ticketId;
	}

	public JIssueTicket(Long issueId, Long ticketId) {
		this.issueId = issueId;
		this.ticketId = ticketId;
	}

	public Long getIssueId() {
		return this.issueId;
	}

	public void setIssueId(Long issueId) {
		this.issueId = issueId;
	}

	public Long getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Long ticketId) {
		this.ticketId = ticketId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JIssueTicket (");

		sb.append(issueId);
		sb.append(", ").append(ticketId);

		sb.append(")");
		return sb.toString();
	}
}
