/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.pojos;

import com.epam.ta.reportportal.store.jooq.enums.JLaunchModeEnum;
import com.epam.ta.reportportal.store.jooq.enums.JStatusEnum;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.4" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLaunch implements Serializable {

	private static final long serialVersionUID = 699714548;

	private Long id;
	private Integer projectId;
	private Integer userId;
	private String name;
	private String description;
	private Timestamp startTime;
	private Integer number;
	private Timestamp lastModified;
	private JLaunchModeEnum mode;
	private JStatusEnum status;

	public JLaunch() {
	}

	public JLaunch(JLaunch value) {
		this.id = value.id;
		this.projectId = value.projectId;
		this.userId = value.userId;
		this.name = value.name;
		this.description = value.description;
		this.startTime = value.startTime;
		this.number = value.number;
		this.lastModified = value.lastModified;
		this.mode = value.mode;
		this.status = value.status;
	}

	public JLaunch(Long id, Integer projectId, Integer userId, String name, String description, Timestamp startTime, Integer number,
			Timestamp lastModified, JLaunchModeEnum mode, JStatusEnum status) {
		this.id = id;
		this.projectId = projectId;
		this.userId = userId;
		this.name = name;
		this.description = description;
		this.startTime = startTime;
		this.number = number;
		this.lastModified = lastModified;
		this.mode = mode;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Timestamp getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Timestamp getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Timestamp lastModified) {
		this.lastModified = lastModified;
	}

	public JLaunchModeEnum getMode() {
		return this.mode;
	}

	public void setMode(JLaunchModeEnum mode) {
		this.mode = mode;
	}

	public JStatusEnum getStatus() {
		return this.status;
	}

	public void setStatus(JStatusEnum status) {
		this.status = status;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JLaunch (");

		sb.append(id);
		sb.append(", ").append(projectId);
		sb.append(", ").append(userId);
		sb.append(", ").append(name);
		sb.append(", ").append(description);
		sb.append(", ").append(startTime);
		sb.append(", ").append(number);
		sb.append(", ").append(lastModified);
		sb.append(", ").append(mode);
		sb.append(", ").append(status);

		sb.append(")");
		return sb.toString();
	}
}
