/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.pojos;

import javax.annotation.Generated;
import java.io.Serializable;
import java.util.Arrays;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JProjectEmailConfiguration implements Serializable {

	private static final long serialVersionUID = -1343422000;

	private Integer id;
	private Boolean enabled;
	private String[] recipients;

	public JProjectEmailConfiguration() {
	}

	public JProjectEmailConfiguration(JProjectEmailConfiguration value) {
		this.id = value.id;
		this.enabled = value.enabled;
		this.recipients = value.recipients;
	}

	public JProjectEmailConfiguration(Integer id, Boolean enabled, String[] recipients) {
		this.id = id;
		this.enabled = enabled;
		this.recipients = recipients;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String[] getRecipients() {
		return this.recipients;
	}

	public void setRecipients(String... recipients) {
		this.recipients = recipients;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JProjectEmailConfiguration (");

		sb.append(id);
		sb.append(", ").append(enabled);
		sb.append(", ").append(Arrays.toString(recipients));

		sb.append(")");
		return sb.toString();
	}
}
