/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables;


import com.epam.reportportal.base.infrastructure.persistence.jooq.JPublic;
import com.epam.reportportal.base.infrastructure.persistence.jooq.Keys;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JIssue.JIssuePath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTicket.JTicketPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records.JIssueTicketRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JIssueTicket extends TableImpl<JIssueTicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.issue_ticket</code>
     */
    public static final JIssueTicket ISSUE_TICKET = new JIssueTicket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JIssueTicketRecord> getRecordType() {
        return JIssueTicketRecord.class;
    }

    /**
     * The column <code>public.issue_ticket.issue_id</code>.
     */
    public final TableField<JIssueTicketRecord, Long> ISSUE_ID = createField(DSL.name("issue_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.issue_ticket.ticket_id</code>.
     */
    public final TableField<JIssueTicketRecord, Long> TICKET_ID = createField(DSL.name("ticket_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private JIssueTicket(Name alias, Table<JIssueTicketRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JIssueTicket(Name alias, Table<JIssueTicketRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.issue_ticket</code> table reference
     */
    public JIssueTicket(String alias) {
        this(DSL.name(alias), ISSUE_TICKET);
    }

    /**
     * Create an aliased <code>public.issue_ticket</code> table reference
     */
    public JIssueTicket(Name alias) {
        this(alias, ISSUE_TICKET);
    }

    /**
     * Create a <code>public.issue_ticket</code> table reference
     */
    public JIssueTicket() {
        this(DSL.name("issue_ticket"), null);
    }

    public <O extends Record> JIssueTicket(Table<O> path, ForeignKey<O, JIssueTicketRecord> childPath, InverseForeignKey<O, JIssueTicketRecord> parentPath) {
        super(path, childPath, parentPath, ISSUE_TICKET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JIssueTicketPath extends JIssueTicket implements Path<JIssueTicketRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JIssueTicketPath(Table<O> path, ForeignKey<O, JIssueTicketRecord> childPath, InverseForeignKey<O, JIssueTicketRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JIssueTicketPath(Name alias, Table<JIssueTicketRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JIssueTicketPath as(String alias) {
            return new JIssueTicketPath(DSL.name(alias), this);
        }

        @Override
        public JIssueTicketPath as(Name alias) {
            return new JIssueTicketPath(alias, this);
        }

        @Override
        public JIssueTicketPath as(Table<?> alias) {
            return new JIssueTicketPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public UniqueKey<JIssueTicketRecord> getPrimaryKey() {
        return Keys.ISSUE_TICKET_PK;
    }

    @Override
    public List<ForeignKey<JIssueTicketRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ISSUE_TICKET__ISSUE_TICKET_ISSUE_ID_FKEY, Keys.ISSUE_TICKET__ISSUE_TICKET_TICKET_ID_FKEY);
    }

    private transient JIssuePath _issue;

    /**
     * Get the implicit join path to the <code>public.issue</code> table.
     */
    public JIssuePath issue() {
        if (_issue == null)
            _issue = new JIssuePath(this, Keys.ISSUE_TICKET__ISSUE_TICKET_ISSUE_ID_FKEY, null);

        return _issue;
    }

    private transient JTicketPath _ticket;

    /**
     * Get the implicit join path to the <code>public.ticket</code> table.
     */
    public JTicketPath ticket() {
        if (_ticket == null)
            _ticket = new JTicketPath(this, Keys.ISSUE_TICKET__ISSUE_TICKET_TICKET_ID_FKEY, null);

        return _ticket;
    }

    @Override
    public JIssueTicket as(String alias) {
        return new JIssueTicket(DSL.name(alias), this);
    }

    @Override
    public JIssueTicket as(Name alias) {
        return new JIssueTicket(alias, this);
    }

    @Override
    public JIssueTicket as(Table<?> alias) {
        return new JIssueTicket(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JIssueTicket rename(String name) {
        return new JIssueTicket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JIssueTicket rename(Name name) {
        return new JIssueTicket(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JIssueTicket rename(Table<?> name) {
        return new JIssueTicket(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JIssueTicket where(Condition condition) {
        return new JIssueTicket(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JIssueTicket where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JIssueTicket where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JIssueTicket where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JIssueTicket where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JIssueTicket where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JIssueTicket where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JIssueTicket where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JIssueTicket whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JIssueTicket whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
