/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables;


import com.epam.reportportal.base.infrastructure.persistence.dao.converters.JooqInstantConverter;
import com.epam.reportportal.base.infrastructure.persistence.jooq.Indexes;
import com.epam.reportportal.base.infrastructure.persistence.jooq.JPublic;
import com.epam.reportportal.base.infrastructure.persistence.jooq.Keys;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JLaunch.JLaunchPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records.JLaunchesModifiedRecord;
import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JLaunchesModified extends TableImpl<JLaunchesModifiedRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>public.launches_modified</code>
   */
  public static final JLaunchesModified LAUNCHES_MODIFIED = new JLaunchesModified();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<JLaunchesModifiedRecord> getRecordType() {
    return JLaunchesModifiedRecord.class;
  }

  /**
   * The column <code>public.launches_modified.launch_id</code>.
   */
  public final TableField<JLaunchesModifiedRecord, Long> LAUNCH_ID = createField(
      DSL.name("launch_id"), SQLDataType.BIGINT.nullable(false), this, "");

  /**
   * The column <code>public.launches_modified.created_at</code>.
   */
  public final TableField<JLaunchesModifiedRecord, Instant> CREATED_AT = createField(
      DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false)
          .defaultValue(DSL.field(DSL.raw("clock_timestamp()"), SQLDataType.LOCALDATETIME)), this,
      "", new JooqInstantConverter());

  private JLaunchesModified(Name alias, Table<JLaunchesModifiedRecord> aliased) {
    this(alias, aliased, (Field<?>[]) null, null);
  }

  private JLaunchesModified(Name alias, Table<JLaunchesModifiedRecord> aliased,
      Field<?>[] parameters, Condition where) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
  }

  /**
   * Create an aliased <code>public.launches_modified</code> table reference
   */
  public JLaunchesModified(String alias) {
    this(DSL.name(alias), LAUNCHES_MODIFIED);
  }

  /**
   * Create an aliased <code>public.launches_modified</code> table reference
   */
  public JLaunchesModified(Name alias) {
    this(alias, LAUNCHES_MODIFIED);
  }

  /**
   * Create a <code>public.launches_modified</code> table reference
   */
  public JLaunchesModified() {
    this(DSL.name("launches_modified"), null);
  }

  public <O extends Record> JLaunchesModified(Table<O> path,
      ForeignKey<O, JLaunchesModifiedRecord> childPath,
      InverseForeignKey<O, JLaunchesModifiedRecord> parentPath) {
    super(path, childPath, parentPath, LAUNCHES_MODIFIED);
  }

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  public static class JLaunchesModifiedPath extends JLaunchesModified implements
      Path<JLaunchesModifiedRecord> {

    private static final long serialVersionUID = 1L;

    public <O extends Record> JLaunchesModifiedPath(Table<O> path,
        ForeignKey<O, JLaunchesModifiedRecord> childPath,
        InverseForeignKey<O, JLaunchesModifiedRecord> parentPath) {
      super(path, childPath, parentPath);
    }

    private JLaunchesModifiedPath(Name alias, Table<JLaunchesModifiedRecord> aliased) {
      super(alias, aliased);
    }

    @Override
    public JLaunchesModifiedPath as(String alias) {
      return new JLaunchesModifiedPath(DSL.name(alias), this);
    }

    @Override
    public JLaunchesModifiedPath as(Name alias) {
      return new JLaunchesModifiedPath(alias, this);
    }

    @Override
    public JLaunchesModifiedPath as(Table<?> alias) {
      return new JLaunchesModifiedPath(alias.getQualifiedName(), this);
    }
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : JPublic.PUBLIC;
  }

  @Override
  public List<Index> getIndexes() {
    return Arrays.asList(Indexes.IDX_LAUNCHES_MODIFIED_CREATED_AT);
  }

  @Override
  public UniqueKey<JLaunchesModifiedRecord> getPrimaryKey() {
    return Keys.LAUNCHES_MODIFIED_PKEY;
  }

  @Override
  public List<ForeignKey<JLaunchesModifiedRecord, ?>> getReferences() {
    return Arrays.asList(Keys.LAUNCHES_MODIFIED__LAUNCHES_MODIFIED_LAUNCH_ID_FKEY);
  }

  private transient JLaunchPath _launch;

  /**
   * Get the implicit join path to the <code>public.launch</code> table.
   */
  public JLaunchPath launch() {
    if (_launch == null) {
      _launch = new JLaunchPath(this, Keys.LAUNCHES_MODIFIED__LAUNCHES_MODIFIED_LAUNCH_ID_FKEY,
          null);
    }

    return _launch;
  }

  @Override
  public JLaunchesModified as(String alias) {
    return new JLaunchesModified(DSL.name(alias), this);
  }

  @Override
  public JLaunchesModified as(Name alias) {
    return new JLaunchesModified(alias, this);
  }

  @Override
  public JLaunchesModified as(Table<?> alias) {
    return new JLaunchesModified(alias.getQualifiedName(), this);
  }

  /**
   * Rename this table
   */
  @Override
  public JLaunchesModified rename(String name) {
    return new JLaunchesModified(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public JLaunchesModified rename(Name name) {
    return new JLaunchesModified(name, null);
  }

  /**
   * Rename this table
   */
  @Override
  public JLaunchesModified rename(Table<?> name) {
    return new JLaunchesModified(name.getQualifiedName(), null);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchesModified where(Condition condition) {
    return new JLaunchesModified(getQualifiedName(), aliased() ? this : null, null, condition);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchesModified where(Collection<? extends Condition> conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchesModified where(Condition... conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchesModified where(Field<Boolean> condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchesModified where(SQL condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchesModified where(@Stringly.SQL String condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchesModified where(@Stringly.SQL String condition, Object... binds) {
    return where(DSL.condition(condition, binds));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchesModified where(@Stringly.SQL String condition, QueryPart... parts) {
    return where(DSL.condition(condition, parts));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchesModified whereExists(Select<?> select) {
    return where(DSL.exists(select));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchesModified whereNotExists(Select<?> select) {
    return where(DSL.notExists(select));
  }
}
