/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables;


import com.epam.reportportal.base.infrastructure.persistence.jooq.Indexes;
import com.epam.reportportal.base.infrastructure.persistence.jooq.JPublic;
import com.epam.reportportal.base.infrastructure.persistence.jooq.Keys;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JLaunch.JLaunchPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JStatisticsField.JStatisticsFieldPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records.JLaunchStatisticsRecord;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JLaunchStatistics extends TableImpl<JLaunchStatisticsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>public.launch_statistics</code>
   */
  public static final JLaunchStatistics LAUNCH_STATISTICS = new JLaunchStatistics();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<JLaunchStatisticsRecord> getRecordType() {
    return JLaunchStatisticsRecord.class;
  }

  /**
   * The column <code>public.launch_statistics.s_id</code>.
   */
  public final TableField<JLaunchStatisticsRecord, Long> S_ID = createField(DSL.name("s_id"),
      SQLDataType.BIGINT.nullable(false).identity(true), this, "");

  /**
   * The column <code>public.launch_statistics.s_counter</code>.
   */
  public final TableField<JLaunchStatisticsRecord, Integer> S_COUNTER = createField(
      DSL.name("s_counter"),
      SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

  /**
   * The column <code>public.launch_LAUNCH_STATISTICS.LAUNCH_ID</code>.
   */
  public final TableField<JLaunchStatisticsRecord, Long> LAUNCH_ID = createField(
      DSL.name("launch_id"), SQLDataType.BIGINT.nullable(false), this, "");

  /**
   * The column <code>public.launch_statistics.statistics_field_id</code>.
   */
  public final TableField<JLaunchStatisticsRecord, Long> STATISTICS_FIELD_ID = createField(
      DSL.name("statistics_field_id"), SQLDataType.BIGINT, this, "");

  private JLaunchStatistics(Name alias, Table<JLaunchStatisticsRecord> aliased) {
    this(alias, aliased, (Field<?>[]) null, null);
  }

  private JLaunchStatistics(Name alias, Table<JLaunchStatisticsRecord> aliased,
      Field<?>[] parameters, Condition where) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
  }

  /**
   * Create an aliased <code>public.launch_statistics</code> table reference
   */
  public JLaunchStatistics(String alias) {
    this(DSL.name(alias), LAUNCH_STATISTICS);
  }

  /**
   * Create an aliased <code>public.launch_statistics</code> table reference
   */
  public JLaunchStatistics(Name alias) {
    this(alias, LAUNCH_STATISTICS);
  }

  /**
   * Create a <code>public.launch_statistics</code> table reference
   */
  public JLaunchStatistics() {
    this(DSL.name("launch_statistics"), null);
  }

  public <O extends Record> JLaunchStatistics(Table<O> path,
      ForeignKey<O, JLaunchStatisticsRecord> childPath,
      InverseForeignKey<O, JLaunchStatisticsRecord> parentPath) {
    super(path, childPath, parentPath, LAUNCH_STATISTICS);
  }

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  public static class JLaunchStatisticsPath extends JLaunchStatistics implements
      Path<JLaunchStatisticsRecord> {

    private static final long serialVersionUID = 1L;

    public <O extends Record> JLaunchStatisticsPath(Table<O> path,
        ForeignKey<O, JLaunchStatisticsRecord> childPath,
        InverseForeignKey<O, JLaunchStatisticsRecord> parentPath) {
      super(path, childPath, parentPath);
    }

    private JLaunchStatisticsPath(Name alias, Table<JLaunchStatisticsRecord> aliased) {
      super(alias, aliased);
    }

    @Override
    public JLaunchStatisticsPath as(String alias) {
      return new JLaunchStatisticsPath(DSL.name(alias), this);
    }

    @Override
    public JLaunchStatisticsPath as(Name alias) {
      return new JLaunchStatisticsPath(alias, this);
    }

    @Override
    public JLaunchStatisticsPath as(Table<?> alias) {
      return new JLaunchStatisticsPath(alias.getQualifiedName(), this);
    }
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : JPublic.PUBLIC;
  }

  @Override
  public List<Index> getIndexes() {
    return Arrays.asList(Indexes.LAUNCH_STATISTICS_LAUNCH_IDX);
  }

  @Override
  public Identity<JLaunchStatisticsRecord, Long> getIdentity() {
    return (Identity<JLaunchStatisticsRecord, Long>) super.getIdentity();
  }

  @Override
  public UniqueKey<JLaunchStatisticsRecord> getPrimaryKey() {
    return Keys.LAUNCH_STATISTICS_PK;
  }

  @Override
  public List<UniqueKey<JLaunchStatisticsRecord>> getUniqueKeys() {
    return Arrays.asList(Keys.UNIQUE_LAUNCH_STATS);
  }

  @Override
  public List<ForeignKey<JLaunchStatisticsRecord, ?>> getReferences() {
    return Arrays.asList(Keys.LAUNCH_STATISTICS__LAUNCH_STATISTICS_LAUNCH_ID_FKEY,
        Keys.LAUNCH_STATISTICS__LAUNCH_STATISTICS_STATISTICS_FIELD_ID_FKEY);
  }

  private transient JLaunchPath _launch;

  /**
   * Get the implicit join path to the <code>public.launch</code> table.
   */
  public JLaunchPath launch() {
    if (_launch == null) {
      _launch = new JLaunchPath(this, Keys.LAUNCH_STATISTICS__LAUNCH_STATISTICS_LAUNCH_ID_FKEY,
          null);
    }

    return _launch;
  }

  private transient JStatisticsFieldPath _statisticsField;

  /**
   * Get the implicit join path to the <code>public.statistics_field</code> table.
   */
  public JStatisticsFieldPath statisticsField() {
    if (_statisticsField == null) {
      _statisticsField = new JStatisticsFieldPath(this,
          Keys.LAUNCH_STATISTICS__LAUNCH_STATISTICS_STATISTICS_FIELD_ID_FKEY, null);
    }

    return _statisticsField;
  }

  @Override
  public List<Check<JLaunchStatisticsRecord>> getChecks() {
    return Arrays.asList(
        Internal.createCheck(this, DSL.name("launch_statistics_s_counter_check"),
            "((s_counter >= 0))", true)
    );
  }

  @Override
  public JLaunchStatistics as(String alias) {
    return new JLaunchStatistics(DSL.name(alias), this);
  }

  @Override
  public JLaunchStatistics as(Name alias) {
    return new JLaunchStatistics(alias, this);
  }

  @Override
  public JLaunchStatistics as(Table<?> alias) {
    return new JLaunchStatistics(alias.getQualifiedName(), this);
  }

  /**
   * Rename this table
   */
  @Override
  public JLaunchStatistics rename(String name) {
    return new JLaunchStatistics(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public JLaunchStatistics rename(Name name) {
    return new JLaunchStatistics(name, null);
  }

  /**
   * Rename this table
   */
  @Override
  public JLaunchStatistics rename(Table<?> name) {
    return new JLaunchStatistics(name.getQualifiedName(), null);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchStatistics where(Condition condition) {
    return new JLaunchStatistics(getQualifiedName(), aliased() ? this : null, null, condition);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchStatistics where(Collection<? extends Condition> conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchStatistics where(Condition... conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchStatistics where(Field<Boolean> condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchStatistics where(SQL condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchStatistics where(@Stringly.SQL String condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchStatistics where(@Stringly.SQL String condition, Object... binds) {
    return where(DSL.condition(condition, binds));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JLaunchStatistics where(@Stringly.SQL String condition, QueryPart... parts) {
    return where(DSL.condition(condition, parts));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchStatistics whereExists(Select<?> select) {
    return where(DSL.exists(select));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JLaunchStatistics whereNotExists(Select<?> select) {
    return where(DSL.notExists(select));
  }
}
