/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables;


import com.epam.reportportal.base.infrastructure.persistence.dao.converters.JooqInstantConverter;
import com.epam.reportportal.base.infrastructure.persistence.jooq.Indexes;
import com.epam.reportportal.base.infrastructure.persistence.jooq.JPublic;
import com.epam.reportportal.base.infrastructure.persistence.jooq.Keys;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records.JRevokedTokenRecord;
import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JRevokedToken extends TableImpl<JRevokedTokenRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>public.revoked_token</code>
   */
  public static final JRevokedToken REVOKED_TOKEN = new JRevokedToken();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<JRevokedTokenRecord> getRecordType() {
    return JRevokedTokenRecord.class;
  }

  /**
   * The column <code>public.revoked_token.id</code>.
   */
  public final TableField<JRevokedTokenRecord, Long> ID = createField(DSL.name("id"),
      SQLDataType.BIGINT.nullable(false).identity(true), this, "");

  /**
   * The column <code>public.revoked_token.jti</code>.
   */
  public final TableField<JRevokedTokenRecord, String> JTI = createField(DSL.name("jti"),
      SQLDataType.VARCHAR(36), this, "");

  /**
   * The column <code>public.revoked_token.subject</code>.
   */
  public final TableField<JRevokedTokenRecord, String> SUBJECT = createField(DSL.name("subject"),
      SQLDataType.VARCHAR(128), this, "");

  /**
   * The column <code>public.revoked_token.revoked_at</code>.
   */
  public final TableField<JRevokedTokenRecord, Instant> REVOKED_AT = createField(
      DSL.name("revoked_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "",
      new JooqInstantConverter());

  private JRevokedToken(Name alias, Table<JRevokedTokenRecord> aliased) {
    this(alias, aliased, (Field<?>[]) null, null);
  }

  private JRevokedToken(Name alias, Table<JRevokedTokenRecord> aliased, Field<?>[] parameters,
      Condition where) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
  }

  /**
   * Create an aliased <code>public.revoked_token</code> table reference
   */
  public JRevokedToken(String alias) {
    this(DSL.name(alias), REVOKED_TOKEN);
  }

  /**
   * Create an aliased <code>public.revoked_token</code> table reference
   */
  public JRevokedToken(Name alias) {
    this(alias, REVOKED_TOKEN);
  }

  /**
   * Create a <code>public.revoked_token</code> table reference
   */
  public JRevokedToken() {
    this(DSL.name("revoked_token"), null);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : JPublic.PUBLIC;
  }

  @Override
  public List<Index> getIndexes() {
    return Arrays.asList(Indexes.IDX_REVOKED_TOKEN_JTI,
        Indexes.IDX_REVOKED_TOKEN_SUBJECT_REVOKED_AT);
  }

  @Override
  public Identity<JRevokedTokenRecord, Long> getIdentity() {
    return (Identity<JRevokedTokenRecord, Long>) super.getIdentity();
  }

  @Override
  public UniqueKey<JRevokedTokenRecord> getPrimaryKey() {
    return Keys.REVOKED_TOKEN_PKEY;
  }

  @Override
  public JRevokedToken as(String alias) {
    return new JRevokedToken(DSL.name(alias), this);
  }

  @Override
  public JRevokedToken as(Name alias) {
    return new JRevokedToken(alias, this);
  }

  @Override
  public JRevokedToken as(Table<?> alias) {
    return new JRevokedToken(alias.getQualifiedName(), this);
  }

  /**
   * Rename this table
   */
  @Override
  public JRevokedToken rename(String name) {
    return new JRevokedToken(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public JRevokedToken rename(Name name) {
    return new JRevokedToken(name, null);
  }

  /**
   * Rename this table
   */
  @Override
  public JRevokedToken rename(Table<?> name) {
    return new JRevokedToken(name.getQualifiedName(), null);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JRevokedToken where(Condition condition) {
    return new JRevokedToken(getQualifiedName(), aliased() ? this : null, null, condition);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JRevokedToken where(Collection<? extends Condition> conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JRevokedToken where(Condition... conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JRevokedToken where(Field<Boolean> condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JRevokedToken where(SQL condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JRevokedToken where(@Stringly.SQL String condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JRevokedToken where(@Stringly.SQL String condition, Object... binds) {
    return where(DSL.condition(condition, binds));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public JRevokedToken where(@Stringly.SQL String condition, QueryPart... parts) {
    return where(DSL.condition(condition, parts));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JRevokedToken whereExists(Select<?> select) {
    return where(DSL.exists(select));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public JRevokedToken whereNotExists(Select<?> select) {
    return where(DSL.notExists(select));
  }
}
