/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.base.infrastructure.persistence.jooq.tables;


import com.epam.reportportal.base.infrastructure.persistence.jooq.Indexes;
import com.epam.reportportal.base.infrastructure.persistence.jooq.JPublic;
import com.epam.reportportal.base.infrastructure.persistence.jooq.Keys;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsAttachment.JTmsAttachmentPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsTestCaseExecution.JTmsTestCaseExecutionPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsTestCaseExecutionCommentAttachment.JTmsTestCaseExecutionCommentAttachmentPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.JTmsTestCaseExecutionCommentBtsTicket.JTmsTestCaseExecutionCommentBtsTicketPath;
import com.epam.reportportal.base.infrastructure.persistence.jooq.tables.records.JTmsTestCaseExecutionCommentRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsTestCaseExecutionComment extends TableImpl<JTmsTestCaseExecutionCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.tms_test_case_execution_comment</code>
     */
    public static final JTmsTestCaseExecutionComment TMS_TEST_CASE_EXECUTION_COMMENT = new JTmsTestCaseExecutionComment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JTmsTestCaseExecutionCommentRecord> getRecordType() {
        return JTmsTestCaseExecutionCommentRecord.class;
    }

    /**
     * The column <code>public.tms_test_case_execution_comment.id</code>.
     */
    public final TableField<JTmsTestCaseExecutionCommentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.tms_test_case_execution_comment.execution_id</code>.
     */
    public final TableField<JTmsTestCaseExecutionCommentRecord, Long> EXECUTION_ID = createField(DSL.name("execution_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tms_test_case_execution_comment.comment</code>.
     */
    public final TableField<JTmsTestCaseExecutionCommentRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.CLOB, this, "");

    private JTmsTestCaseExecutionComment(Name alias, Table<JTmsTestCaseExecutionCommentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JTmsTestCaseExecutionComment(Name alias, Table<JTmsTestCaseExecutionCommentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tms_test_case_execution_comment</code>
     * table reference
     */
    public JTmsTestCaseExecutionComment(String alias) {
        this(DSL.name(alias), TMS_TEST_CASE_EXECUTION_COMMENT);
    }

    /**
     * Create an aliased <code>public.tms_test_case_execution_comment</code>
     * table reference
     */
    public JTmsTestCaseExecutionComment(Name alias) {
        this(alias, TMS_TEST_CASE_EXECUTION_COMMENT);
    }

    /**
     * Create a <code>public.tms_test_case_execution_comment</code> table
     * reference
     */
    public JTmsTestCaseExecutionComment() {
        this(DSL.name("tms_test_case_execution_comment"), null);
    }

    public <O extends Record> JTmsTestCaseExecutionComment(Table<O> path, ForeignKey<O, JTmsTestCaseExecutionCommentRecord> childPath, InverseForeignKey<O, JTmsTestCaseExecutionCommentRecord> parentPath) {
        super(path, childPath, parentPath, TMS_TEST_CASE_EXECUTION_COMMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JTmsTestCaseExecutionCommentPath extends JTmsTestCaseExecutionComment implements Path<JTmsTestCaseExecutionCommentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JTmsTestCaseExecutionCommentPath(Table<O> path, ForeignKey<O, JTmsTestCaseExecutionCommentRecord> childPath, InverseForeignKey<O, JTmsTestCaseExecutionCommentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JTmsTestCaseExecutionCommentPath(Name alias, Table<JTmsTestCaseExecutionCommentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JTmsTestCaseExecutionCommentPath as(String alias) {
            return new JTmsTestCaseExecutionCommentPath(DSL.name(alias), this);
        }

        @Override
        public JTmsTestCaseExecutionCommentPath as(Name alias) {
            return new JTmsTestCaseExecutionCommentPath(alias, this);
        }

        @Override
        public JTmsTestCaseExecutionCommentPath as(Table<?> alias) {
            return new JTmsTestCaseExecutionCommentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TMS_TEST_CASE_EXECUTION_COMMENT_EXECUTION_ID);
    }

    @Override
    public Identity<JTmsTestCaseExecutionCommentRecord, Long> getIdentity() {
        return (Identity<JTmsTestCaseExecutionCommentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<JTmsTestCaseExecutionCommentRecord> getPrimaryKey() {
        return Keys.TMS_TEST_CASE_EXECUTION_COMMENT_PK;
    }

    @Override
    public List<UniqueKey<JTmsTestCaseExecutionCommentRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TMS_TEST_CASE_EXECUTION_COMMENT_EXECUTION_ID_KEY);
    }

    @Override
    public List<ForeignKey<JTmsTestCaseExecutionCommentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TMS_TEST_CASE_EXECUTION_COMMENT__TMS_TEST_CASE_EXECUTION_COMMENT_FK_EXECUTION);
    }

    private transient JTmsTestCaseExecutionPath _tmsTestCaseExecution;

    /**
     * Get the implicit join path to the
     * <code>public.tms_test_case_execution</code> table.
     */
    public JTmsTestCaseExecutionPath tmsTestCaseExecution() {
        if (_tmsTestCaseExecution == null)
            _tmsTestCaseExecution = new JTmsTestCaseExecutionPath(this, Keys.TMS_TEST_CASE_EXECUTION_COMMENT__TMS_TEST_CASE_EXECUTION_COMMENT_FK_EXECUTION, null);

        return _tmsTestCaseExecution;
    }

    private transient JTmsTestCaseExecutionCommentAttachmentPath _tmsTestCaseExecutionCommentAttachment;

    /**
     * Get the implicit to-many join path to the
     * <code>public.tms_test_case_execution_comment_attachment</code> table
     */
    public JTmsTestCaseExecutionCommentAttachmentPath tmsTestCaseExecutionCommentAttachment() {
        if (_tmsTestCaseExecutionCommentAttachment == null)
            _tmsTestCaseExecutionCommentAttachment = new JTmsTestCaseExecutionCommentAttachmentPath(this, null, Keys.TMS_TEST_CASE_EXECUTION_COMMENT_ATTACHMENT__TMS_TEST_CASE_EXECUTION_COMMENT_ATTACHMENT_FK_COMMENT.getInverseKey());

        return _tmsTestCaseExecutionCommentAttachment;
    }

    private transient JTmsTestCaseExecutionCommentBtsTicketPath _tmsTestCaseExecutionCommentBtsTicket;

    /**
     * Get the implicit to-many join path to the
     * <code>public.tms_test_case_execution_comment_bts_ticket</code> table
     */
    public JTmsTestCaseExecutionCommentBtsTicketPath tmsTestCaseExecutionCommentBtsTicket() {
        if (_tmsTestCaseExecutionCommentBtsTicket == null)
            _tmsTestCaseExecutionCommentBtsTicket = new JTmsTestCaseExecutionCommentBtsTicketPath(this, null, Keys.TMS_TEST_CASE_EXECUTION_COMMENT_BTS_TICKET__TMS_TEST_CASE_EXECUTION_COMMENT_BTS_TICKET_FK_COMMENT.getInverseKey());

        return _tmsTestCaseExecutionCommentBtsTicket;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.tms_attachment</code> table
     */
    public JTmsAttachmentPath tmsAttachment() {
        return tmsTestCaseExecutionCommentAttachment().tmsAttachment();
    }

    @Override
    public JTmsTestCaseExecutionComment as(String alias) {
        return new JTmsTestCaseExecutionComment(DSL.name(alias), this);
    }

    @Override
    public JTmsTestCaseExecutionComment as(Name alias) {
        return new JTmsTestCaseExecutionComment(alias, this);
    }

    @Override
    public JTmsTestCaseExecutionComment as(Table<?> alias) {
        return new JTmsTestCaseExecutionComment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JTmsTestCaseExecutionComment rename(String name) {
        return new JTmsTestCaseExecutionComment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JTmsTestCaseExecutionComment rename(Name name) {
        return new JTmsTestCaseExecutionComment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JTmsTestCaseExecutionComment rename(Table<?> name) {
        return new JTmsTestCaseExecutionComment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsTestCaseExecutionComment where(Condition condition) {
        return new JTmsTestCaseExecutionComment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsTestCaseExecutionComment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsTestCaseExecutionComment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsTestCaseExecutionComment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsTestCaseExecutionComment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsTestCaseExecutionComment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsTestCaseExecutionComment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsTestCaseExecutionComment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsTestCaseExecutionComment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsTestCaseExecutionComment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
