/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.epam.ta.reportportal.util;

import com.github.slugify.Slugify;
import java.util.function.Function;

/**
 * Utility class for generating slugs from strings.
 *
 * <p>This class uses the {@link Slugify} library to create slugs, which are URL-friendly
 * representations of strings. The slugs are generated by replacing spaces, underscores and special
 * characters with hyphens and lowercasing the string.
 *
 * @author <a href="mailto:Reingold_Shekhtel@epam.com">Reingold Shekhtel</a>
 */
public class SlugUtils {

  private static final Slugify slug = Slugify.builder()
      .customReplacement("_", "-")
      .build();

  /**
   * Generates a slug from the given input string.
   *
   * @param inputStr the input string to be converted to a slug
   * @return the generated slug
   */
  public static String slug(String inputStr) {
    return slug.slugify(inputStr);
  }

  /**
   * A function that converts a string to a slug.
   */
  public static final Function<String, String> TO_SLUG = slug::slugify;
}

