/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.epam.reportportal.base.model.marketplace;

import static java.util.stream.Collectors.toCollection;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import com.epam.reportportal.base.core.configs.JacksonConfiguration;
import com.epam.reportportal.base.model.marketplace.catalogue.AvailablePluginResource;
import com.epam.reportportal.base.model.marketplace.catalogue.InstalledPluginResource;
import com.epam.reportportal.base.model.marketplace.catalogue.MarketplaceAdvisoryResource;
import com.epam.reportportal.base.model.marketplace.catalogue.MarketplaceBlockedResource;
import com.epam.reportportal.base.model.marketplace.catalogue.MarketplaceCatalogueResource;
import com.epam.reportportal.base.model.marketplace.catalogue.MarketplaceEntryResource;
import com.epam.reportportal.base.model.marketplace.catalogue.MarketplaceRemovedResource;
import com.epam.reportportal.base.model.marketplace.catalogue.RegistryStatus;
import com.epam.reportportal.base.model.marketplace.catalogue.RegistryStatusResource;
import com.epam.reportportal.base.model.marketplace.catalogue.UpdateAvailableResource;
import com.epam.reportportal.base.model.marketplace.detail.MarketplaceChangelogResource;
import com.epam.reportportal.base.model.marketplace.detail.MarketplacePluginDetailResource;
import com.epam.reportportal.base.model.marketplace.detail.MarketplacePluginResource;
import com.epam.reportportal.base.model.marketplace.detail.MarketplaceVersionResource;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import org.junit.jupiter.api.Test;

/**
 * The names service-api actually puts on the wire for the plugins page, pinned — and published, so
 * the consumer can eat them.
 *
 * <p>The UI destructures these responses by field name; nothing else does. Renaming or dropping
 * one compiles, passes every other test, and breaks a badge or a block silently. Pinning the names
 * here was never enough on its own: an expectation written beside the record only ever proves the
 * record equals itself, and while the UI fed its own tests hand-made objects the two services
 * could be, and were, wrong together.
 *
 * <p>So this test also writes the serialised responses out, into service-ui's
 * {@code controllers/plugins/__fixtures__}, and the UI's tests read those files instead of
 * inventing their own. The producer publishes the truth; a shape change here fails the consumer's
 * tests on the next run rather than in production.
 *
 * <p>When this fails: if the UI changed with you, update the list in the same commit; if it did
 * not, the change is a break and the field goes back.
 */
class MarketplaceWireContractTest {

  private final ObjectMapper objectMapper = new JacksonConfiguration().objectMapper();

  /**
   * The consumer's directory. Overridable so a checkout laid out differently, or a CI job that
   * wants the fixtures somewhere else, does not have to move a repository to run this.
   */
  private static final Path CONSUMER = Path.of(System.getProperty("marketplace.fixtures.dir",
      "../service-ui/app/src/controllers/plugins")).toAbsolutePath().normalize();

  private static final Path FIXTURES = CONSUMER.resolve("__fixtures__");

  private static final String README = """
      # Marketplace wire fixtures

      Generated by `MarketplaceWireContractTest` in service-api
      (`src/test/java/com/epam/reportportal/base/model/marketplace/MarketplaceWireContractTest.java`).

      **Do not hand-edit.** Every file here is a real response body, produced by serialising real
      resource records with service-api's own ObjectMapper. Editing one by hand would put this
      directory back where it started: a set of invented fixtures that the UI's tests pass against
      and the running service does not match.

      To change a fixture, change the response in service-api and re-run:

          ./gradlew test --tests '*MarketplaceWireContractTest'

      Absent fields are absent on purpose: the service serialises with `NON_NULL`, so a `null` is
      never sent and the UI must treat "missing" and "null" as the same thing.

      | File | Route | State |
      | --- | --- | --- |
      | `catalogue.json` | `GET /v1/plugins` | registry online: installed matched, installed unmatched, installed removed, available, premium locked, advisory, blocked, update available |
      | `catalogue-offline.json` | `GET /v1/plugins` | registry unreachable: local rows only, no marketplace block, nothing available |
      | `plugin-detail.json` | `GET /v1/plugins/{registryId}` | registry online: manifest, version history, changelog, screenshots, advisory, blocked, premium locked |
      | `plugin-detail-removed.json` | `GET /v1/plugins/{registryId}` | registry online: tombstone only — removed from the marketplace, still running here |
      | `plugin-detail-offline.json` | `GET /v1/plugins/{registryId}` | registry unreachable: the envelope and nothing registry-derived |
      """;

  /**
   * GET /v1/plugins. Nested objects are listed by path, because the UI reads them by path too.
   */
  private static final List<String> CATALOGUE_FIELDS = List.of(
      "available[].access",
      "available[].contactUrl",
      "available[].description",
      "available[].groupType",
      "available[].id",
      "available[].latestVersion",
      "available[].locked",
      "available[].name",
      "available[].tier",
      "installed[].enabled",
      "installed[].groupType",
      "installed[].integrationTypeId",
      "installed[].marketplace.access",
      "installed[].marketplace.advisory.attachedAt",
      "installed[].marketplace.advisory.severity",
      "installed[].marketplace.advisory.text",
      "installed[].marketplace.blocked.blockedAt",
      "installed[].marketplace.blocked.reason",
      "installed[].marketplace.blocked.version",
      "installed[].marketplace.latestVersion",
      "installed[].marketplace.locked",
      "installed[].marketplace.pluginId",
      "installed[].marketplace.removed.removalReason",
      "installed[].marketplace.removed.removed",
      "installed[].marketplace.removed.removedBy",
      "installed[].marketplace.tier",
      "installed[].marketplace.updateAvailable.version",
      "installed[].name",
      "installed[].version",
      "registry.host",
      "registry.status"
  );

  /**
   * GET /v1/plugins/{registryId}, across the published and the removed answer. It carries the same
   * {@code registry} envelope the catalogue does: the UI has one rule for whether a
   * marketplace-sourced signal may be believed, and that rule reads the envelope.
   */
  private static final List<String> PLUGIN_DETAIL_FIELDS = List.of(
      "advisory.attachedAt",
      "advisory.severity",
      "advisory.text",
      "blocked.blockedAt",
      "blocked.reason",
      "blocked.version",
      "changelog.lines[]",
      "changelog.version",
      "locked",
      "plugin.access",
      "plugin.description",
      "plugin.id",
      "plugin.latestVersion",
      "plugin.name",
      "plugin.tier",
      "registry.host",
      "registry.status",
      "removed.removalReason",
      "removed.removed",
      "removed.removedBy",
      "screenshots[]",
      "versions[].blocked",
      "versions[].publishedAt",
      "versions[].version"
  );

  /**
   * The files the consumer imports by name. Checked in beside the fixtures themselves, because a
   * fixture that quietly stops being published leaves the UI importing a file that is merely stale
   * — or, once someone deletes it, one that is not there at all.
   */
  private static final List<String> PUBLISHED = List.of(
      "README.md",
      "catalogue-offline.json",
      "catalogue.json",
      "plugin-detail-offline.json",
      "plugin-detail-removed.json",
      "plugin-detail.json"
  );

  private static final String HOST = "marketplace.reportportal.io";
  private static final Instant WHEN = Instant.parse("2026-03-12T10:15:30Z");
  private static final Instant EARLIER = Instant.parse("2026-01-05T12:00:00Z");

  private static RegistryStatusResource online() {
    return new RegistryStatusResource(RegistryStatus.ONLINE, HOST);
  }

  private static RegistryStatusResource offline() {
    return new RegistryStatusResource(RegistryStatus.OFFLINE, HOST);
  }

  private static MarketplaceAdvisoryResource advisory() {
    return new MarketplaceAdvisoryResource("high", "Leaks the API key into the log", WHEN);
  }

  private static MarketplaceRemovedResource removed() {
    return new MarketplaceRemovedResource(EARLIER, "Vendor withdrew it", "operator@rp.io");
  }

  /** The plugin whose installed version has both a badge and an update waiting. */
  private static InstalledPluginResource installedMatched() {
    return new InstalledPluginResource(7L, "jira", "1.5.2", true, "BTS",
        new MarketplaceEntryResource("plugin-bts-jira", "premium", "official", "1.6.0",
            new UpdateAvailableResource("1.6.0"), advisory(),
            new MarketplaceBlockedResource("1.5.2", WHEN, "Signed with a revoked key"), null,
            true));
  }

  /** Matched, current, nothing wrong with it — the row every badge rule must leave alone. */
  private static InstalledPluginResource installedClean() {
    return new InstalledPluginResource(8L, "rally", "5.0.0", true, "BTS",
        new MarketplaceEntryResource("plugin-bts-rally", "public", "official", "5.0.0", null, null,
            null, null, false));
  }

  /** Removed from the marketplace, still running here: a tombstone on an otherwise bare block. */
  private static InstalledPluginResource installedRemoved() {
    return new InstalledPluginResource(9L, "gitlab", "2.1.0", false, "BTS",
        new MarketplaceEntryResource("plugin-bts-gitlab", null, null, null, null, null, null,
            removed(), false));
  }

  /**
   * Installed here and not matched to any registry entry. The block is absent, and with it the
   * registry id — there is no known registry id for a plugin the registry was never able to
   * confirm, so there is nowhere else on the row for one to sit.
   */
  private static InstalledPluginResource installedUnmatched() {
    return new InstalledPluginResource(10L, "custom-scanner", "0.9.0", true, "OTHER", null);
  }

  private static MarketplaceCatalogueResource catalogue() {
    return new MarketplaceCatalogueResource(online(),
        List.of(installedMatched(), installedClean(), installedRemoved(), installedUnmatched()),
        List.of(
            new AvailablePluginResource("plugin-notify-slack", "Slack", "2.0.0",
                "Posts a message when a launch finishes", null, "NOTIFICATION", "public",
                "official", false),
            new AvailablePluginResource("plugin-bts-azure", "Azure DevOps", "1.2.0",
                "Tracks issues in Azure Boards", "https://reportportal.io/contact", "BTS",
                "premium", "verified", true)));
  }

  /**
   * The registry could not be reached. The local rows survive, stripped of every marketplace-
   * sourced claim, and nothing is offered for install.
   */
  private static MarketplaceCatalogueResource offlineCatalogue() {
    return new MarketplaceCatalogueResource(offline(),
        List.of(new InstalledPluginResource(7L, "jira", "1.5.2", true, "BTS", null),
            installedUnmatched()),
        List.of());
  }

  private static MarketplacePluginDetailResource pluginDetail() {
    return new MarketplacePluginDetailResource(online(),
        new MarketplacePluginResource("plugin-bts-jira", "Jira", "Tracks issues in Jira", "1.6.0",
            "premium", "official"),
        List.of(new MarketplaceVersionResource("1.6.0", WHEN, false),
            new MarketplaceVersionResource("1.5.2", EARLIER, true)),
        new MarketplaceChangelogResource("1.6.0",
            List.of("Fixed a crash on an empty summary", "Dropped the legacy field")),
        List.of("https://cdn.rp.io/jira/1.png", "https://cdn.rp.io/jira/2.png"),
        advisory(),
        new MarketplaceBlockedResource("1.6.0", WHEN, "Signed with a revoked key"),
        null,
        true);
  }

  /** The registry answered with a tombstone: the id survives, the manifest does not. */
  private static MarketplacePluginDetailResource removedPluginDetail() {
    return new MarketplacePluginDetailResource(online(),
        new MarketplacePluginResource("plugin-bts-gitlab", null, null, null, null, null),
        List.of(), null, List.of(), null, null, removed(), false);
  }

  private static MarketplacePluginDetailResource offlinePluginDetail() {
    return new MarketplacePluginDetailResource(offline(), null, List.of(), null, List.of(), null,
        null, null, false);
  }

  /** Every fixture, by the file name the consumer imports it under. */
  private static Map<String, Object> fixtures() {
    var fixtures = new LinkedHashMap<String, Object>();
    fixtures.put("catalogue.json", catalogue());
    fixtures.put("catalogue-offline.json", offlineCatalogue());
    fixtures.put("plugin-detail.json", pluginDetail());
    fixtures.put("plugin-detail-removed.json", removedPluginDetail());
    fixtures.put("plugin-detail-offline.json", offlinePluginDetail());
    return fixtures;
  }

  @Test
  void theCatalogueEmitsExactlyTheFieldNamesTheUiReads() {
    assertFields(CATALOGUE_FIELDS, "GET /v1/plugins", catalogue());
  }

  @Test
  void thePluginDetailEmitsExactlyTheFieldNamesTheUiReads() {
    assertFields(PLUGIN_DETAIL_FIELDS, "GET /v1/plugins/{registryId}", pluginDetail(),
        removedPluginDetail());
  }

  /**
   * The registry id is a marketplace-sourced fact, so it lives inside the marketplace block and
   * nowhere else. With no block there is no known registry id, and the row says so by carrying
   * none — an invariant of the shape rather than something two places have to keep in step.
   */
  @Test
  void anInstalledRowWithNoMarketplaceBlockCarriesNoRegistryIdAnywhere() {
    var unmatched = objectMapper.valueToTree(installedUnmatched());

    assertTrue(unmatched.path("marketplace").isMissingNode(),
        "an unmatched row must carry no marketplace block");
    assertEquals(List.of(), pathsEndingIn(unmatched, "pluginId"),
        "with no marketplace block there is no known registry id, so none may be on the row");

    // And when there is a block, the id is in it — the one place the UI is told to read.
    assertEquals(List.of("marketplace.pluginId"),
        pathsEndingIn(objectMapper.valueToTree(installedMatched()), "pluginId"));
  }

  /**
   * Offline is a 200 that says the registry could not be asked, not a page with blanks in it.
   * Every registry-derived field is absent, so nothing on either screen can be believed by
   * accident.
   */
  @Test
  void theOfflineEnvelopesCarryTheStatusAndTheHostAndNothingRegistryDerived() {
    var page = objectMapper.valueToTree(offlinePluginDetail());
    assertEquals("OFFLINE", page.path("registry").path("status").asText());
    assertEquals(HOST, page.path("registry").path("host").asText());
    assertEquals(new TreeSet<>(List.of("locked", "registry", "screenshots", "versions")),
        new TreeSet<>(names(page)));
    assertTrue(page.path("versions").isEmpty());
    assertTrue(page.path("screenshots").isEmpty());

    var list = objectMapper.valueToTree(offlineCatalogue());
    assertEquals("OFFLINE", list.path("registry").path("status").asText());
    assertEquals(HOST, list.path("registry").path("host").asText());
    assertTrue(list.path("available").isEmpty());
    assertEquals(List.of(), pathsEndingIn(list, "marketplace"),
        "an offline catalogue can vouch for nothing, so no row carries a marketplace block");
  }

  /**
   * Publishes the fixtures the UI's tests read. They are written from the same records the
   * assertions above run over, through the service's own mapper, so what the consumer eats is
   * what this service emits.
   */
  @Test
  void theSerialisedResponsesArePublishedForTheUiToConsume() throws IOException {
    assumeTrue(Files.isDirectory(CONSUMER),
        "service-ui is not checked out at " + CONSUMER + "; nothing to publish to");
    Files.createDirectories(FIXTURES);
    Files.writeString(FIXTURES.resolve("README.md"), README);

    var writer = objectMapper.writerWithDefaultPrettyPrinter();
    for (var fixture : fixtures().entrySet()) {
      Files.writeString(FIXTURES.resolve(fixture.getKey()),
          writer.writeValueAsString(fixture.getValue()) + "\n");
    }

    // The directory holds exactly what the consumer imports: no fixture silently dropped, and
    // none left behind by a rename.
    try (var listing = Files.list(FIXTURES)) {
      assertEquals(new TreeSet<>(PUBLISHED),
          listing.map(file -> file.getFileName().toString()).collect(toCollection(TreeSet::new)),
          FIXTURES + " does not hold exactly the files the UI imports");
    }

    // Read them back rather than trust the write: a fixture the consumer cannot parse, or one
    // that lost a field on the way out, is worse than none.
    for (var fixture : fixtures().entrySet()) {
      var path = FIXTURES.resolve(fixture.getKey());
      assertTrue(Files.exists(path), path + " was not published");
      assertEquals(objectMapper.writeValueAsString(fixture.getValue()),
          objectMapper.writeValueAsString(objectMapper.readTree(Files.readString(path))),
          fixture.getKey() + " does not round-trip to the response it was made from");
    }
  }

  /**
   * Serialises the resources and compares the paths they actually emitted with the checked-in
   * list, naming what appeared and what went missing. More than one resource may be given: a
   * route's contract is every field it can emit, and no single answer carries them all.
   */
  private void assertFields(List<String> expected, String route, Object... resources) {
    var actual = new TreeSet<String>();
    for (var resource : resources) {
      collect(objectMapper.valueToTree(resource), "", actual);
    }
    var missing = new ArrayList<>(expected);
    missing.removeAll(actual);
    var unexpected = new ArrayList<>(actual);
    unexpected.removeAll(expected);
    assertEquals(new TreeSet<>(expected), actual,
        route + " no longer emits the fields the UI reads."
            + " Dropped or renamed: " + missing + ". Not in the contract: " + unexpected
            + ". Update service-ui in the same commit, or put the field back.");
  }

  /**
   * Every leaf path of the serialised tree. An array contributes {@code []} once rather than one
   * path per element: the contract is about names, not about how many rows a fixture happens to
   * carry. An empty array contributes nothing — it names no leaves, and every array here is
   * populated in at least one of the answers a route can give.
   */
  private static void collect(JsonNode node, String path, TreeSet<String> into) {
    if (node.isObject()) {
      node.properties().forEach(field ->
          collect(field.getValue(), path.isEmpty() ? field.getKey() : path + "." + field.getKey(),
              into));
    } else if (node.isArray()) {
      node.forEach(element -> collect(element, path + "[]", into));
    } else {
      into.add(path);
    }
  }

  /** Every path in the tree whose last segment is {@code name}, wherever it sits. */
  private static List<String> pathsEndingIn(JsonNode node, String name) {
    var found = new ArrayList<String>();
    walk(node, "", name, found);
    return found;
  }

  private static void walk(JsonNode node, String path, String name, List<String> found) {
    if (node.isObject()) {
      node.properties().forEach(field -> {
        var child = path.isEmpty() ? field.getKey() : path + "." + field.getKey();
        if (field.getKey().equals(name)) {
          found.add(child);
        }
        walk(field.getValue(), child, name, found);
      });
    } else if (node.isArray()) {
      node.forEach(element -> walk(element, path + "[]", name, found));
    }
  }

  private static List<String> names(JsonNode node) {
    var names = new ArrayList<String>();
    node.fieldNames().forEachRemaining(names::add);
    return names;
  }
}
