/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.infrastructure.persistence.jooq.tables;


import com.epam.reportportal.infrastructure.persistence.jooq.Indexes;
import com.epam.reportportal.infrastructure.persistence.jooq.JPublic;
import com.epam.reportportal.infrastructure.persistence.jooq.Keys;
import com.epam.reportportal.infrastructure.persistence.jooq.tables.JTestItem.JTestItemPath;
import com.epam.reportportal.infrastructure.persistence.jooq.tables.records.JTmsStepExecutionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsStepExecution extends TableImpl<JTmsStepExecutionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tms_step_execution</code>
     */
    public static final JTmsStepExecution TMS_STEP_EXECUTION = new JTmsStepExecution();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JTmsStepExecutionRecord> getRecordType() {
        return JTmsStepExecutionRecord.class;
    }

    /**
     * The column <code>public.tms_step_execution.id</code>.
     */
    public final TableField<JTmsStepExecutionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.tms_step_execution.test_case_execution_id</code>.
     */
    public final TableField<JTmsStepExecutionRecord, Long> TEST_CASE_EXECUTION_ID = createField(DSL.name("test_case_execution_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tms_step_execution.test_item_id</code>.
     */
    public final TableField<JTmsStepExecutionRecord, Long> TEST_ITEM_ID = createField(DSL.name("test_item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tms_step_execution.launch_id</code>.
     */
    public final TableField<JTmsStepExecutionRecord, Long> LAUNCH_ID = createField(DSL.name("launch_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tms_step_execution.tms_step_id</code>.
     */
    public final TableField<JTmsStepExecutionRecord, Long> TMS_STEP_ID = createField(DSL.name("tms_step_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private JTmsStepExecution(Name alias, Table<JTmsStepExecutionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JTmsStepExecution(Name alias, Table<JTmsStepExecutionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tms_step_execution</code> table reference
     */
    public JTmsStepExecution(String alias) {
        this(DSL.name(alias), TMS_STEP_EXECUTION);
    }

    /**
     * Create an aliased <code>public.tms_step_execution</code> table reference
     */
    public JTmsStepExecution(Name alias) {
        this(alias, TMS_STEP_EXECUTION);
    }

    /**
     * Create a <code>public.tms_step_execution</code> table reference
     */
    public JTmsStepExecution() {
        this(DSL.name("tms_step_execution"), null);
    }

    public <O extends Record> JTmsStepExecution(Table<O> path, ForeignKey<O, JTmsStepExecutionRecord> childPath, InverseForeignKey<O, JTmsStepExecutionRecord> parentPath) {
        super(path, childPath, parentPath, TMS_STEP_EXECUTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JTmsStepExecutionPath extends JTmsStepExecution implements Path<JTmsStepExecutionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JTmsStepExecutionPath(Table<O> path, ForeignKey<O, JTmsStepExecutionRecord> childPath, InverseForeignKey<O, JTmsStepExecutionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JTmsStepExecutionPath(Name alias, Table<JTmsStepExecutionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JTmsStepExecutionPath as(String alias) {
            return new JTmsStepExecutionPath(DSL.name(alias), this);
        }

        @Override
        public JTmsStepExecutionPath as(Name alias) {
            return new JTmsStepExecutionPath(alias, this);
        }

        @Override
        public JTmsStepExecutionPath as(Table<?> alias) {
            return new JTmsStepExecutionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TMS_STEP_EXECUTION_LAUNCH, Indexes.IDX_TMS_STEP_EXECUTION_TEST_CASE, Indexes.IDX_TMS_STEP_EXECUTION_TEST_ITEM, Indexes.IDX_TMS_STEP_EXECUTION_TMS_STEP);
    }

    @Override
    public Identity<JTmsStepExecutionRecord, Long> getIdentity() {
        return (Identity<JTmsStepExecutionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<JTmsStepExecutionRecord> getPrimaryKey() {
        return Keys.TMS_STEP_EXECUTION_PKEY;
    }

    @Override
    public List<ForeignKey<JTmsStepExecutionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TMS_STEP_EXECUTION__TMS_STEP_EXECUTION_TEST_ITEM_FK_TEST_ITEM);
    }

    private transient JTestItemPath _testItem;

    /**
     * Get the implicit join path to the <code>public.test_item</code> table.
     */
    public JTestItemPath testItem() {
        if (_testItem == null)
            _testItem = new JTestItemPath(this, Keys.TMS_STEP_EXECUTION__TMS_STEP_EXECUTION_TEST_ITEM_FK_TEST_ITEM, null);

        return _testItem;
    }

    @Override
    public JTmsStepExecution as(String alias) {
        return new JTmsStepExecution(DSL.name(alias), this);
    }

    @Override
    public JTmsStepExecution as(Name alias) {
        return new JTmsStepExecution(alias, this);
    }

    @Override
    public JTmsStepExecution as(Table<?> alias) {
        return new JTmsStepExecution(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JTmsStepExecution rename(String name) {
        return new JTmsStepExecution(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JTmsStepExecution rename(Name name) {
        return new JTmsStepExecution(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JTmsStepExecution rename(Table<?> name) {
        return new JTmsStepExecution(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsStepExecution where(Condition condition) {
        return new JTmsStepExecution(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsStepExecution where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsStepExecution where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsStepExecution where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsStepExecution where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsStepExecution where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsStepExecution where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JTmsStepExecution where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsStepExecution whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JTmsStepExecution whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
