/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.records;

import com.epam.ta.reportportal.store.jooq.enums.JBtsTypeEnum;
import com.epam.ta.reportportal.store.jooq.tables.JBugTrackingSystem;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JBugTrackingSystemRecord extends UpdatableRecordImpl<JBugTrackingSystemRecord>
		implements Record3<Integer, String, JBtsTypeEnum> {

	private static final long serialVersionUID = -1571680292;

	/**
	 * Setter for <code>public.bug_tracking_system.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.bug_tracking_system.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>public.bug_tracking_system.url</code>.
	 */
	public void setUrl(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>public.bug_tracking_system.url</code>.
	 */
	public String getUrl() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>public.bug_tracking_system.type</code>.
	 */
	public void setType(JBtsTypeEnum value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.bug_tracking_system.type</code>.
	 */
	public JBtsTypeEnum getType() {
		return (JBtsTypeEnum) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, JBtsTypeEnum> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, JBtsTypeEnum> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return JBugTrackingSystem.BUG_TRACKING_SYSTEM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return JBugTrackingSystem.BUG_TRACKING_SYSTEM.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<JBtsTypeEnum> field3() {
		return JBugTrackingSystem.BUG_TRACKING_SYSTEM.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component2() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JBtsTypeEnum component3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JBtsTypeEnum value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JBugTrackingSystemRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JBugTrackingSystemRecord value2(String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JBugTrackingSystemRecord value3(JBtsTypeEnum value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JBugTrackingSystemRecord values(Integer value1, String value2, JBtsTypeEnum value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JBugTrackingSystemRecord
	 */
	public JBugTrackingSystemRecord() {
		super(JBugTrackingSystem.BUG_TRACKING_SYSTEM);
	}

	/**
	 * Create a detached, initialised JBugTrackingSystemRecord
	 */
	public JBugTrackingSystemRecord(Integer id, String url, JBtsTypeEnum type) {
		super(JBugTrackingSystem.BUG_TRACKING_SYSTEM);

		set(0, id);
		set(1, url);
		set(2, type);
	}
}
