/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.records;

import com.epam.ta.reportportal.store.jooq.tables.JDashboard;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDashboardRecord extends UpdatableRecordImpl<JDashboardRecord>
		implements Record5<Integer, String, String, Integer, Timestamp> {

	private static final long serialVersionUID = -537406197;

    /**
     * Setter for <code>public.dashboard.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dashboard.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.dashboard.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dashboard.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

	/**
	 * Setter for <code>public.dashboard.description</code>.
	 */
	public void setDescription(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.dashboard.description</code>.
	 */
	public String getDescription() {
		return (String) get(2);
	}

    /**
     * Setter for <code>public.dashboard.project_id</code>.
     */
    public void setProjectId(Integer value) {
		set(3, value);
	}

    /**
     * Getter for <code>public.dashboard.project_id</code>.
     */
    public Integer getProjectId() {
		return (Integer) get(3);
	}

    /**
     * Setter for <code>public.dashboard.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
		set(4, value);
	}

    /**
     * Getter for <code>public.dashboard.creation_date</code>.
     */
    public Timestamp getCreationDate() {
		return (Timestamp) get(4);
	}

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
	public Row5<Integer, String, String, Integer, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

    /**
     * {@inheritDoc}
     */
    @Override
	public Row5<Integer, String, String, Integer, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JDashboard.DASHBOARD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JDashboard.DASHBOARD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public Field<String> field3() {
		return JDashboard.DASHBOARD.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return JDashboard.DASHBOARD.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public Field<Timestamp> field5() {
		return JDashboard.DASHBOARD.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public String component3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component4() {
		return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public Timestamp component5() {
		return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public Timestamp value5() {
		return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDashboardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDashboardRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public JDashboardRecord value3(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JDashboardRecord value4(Integer value) {
		setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public JDashboardRecord value5(Timestamp value) {
		setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public JDashboardRecord values(Integer value1, String value2, String value3, Integer value4, Timestamp value5) {
		value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
		value5(value5);
		return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDashboardRecord
     */
    public JDashboardRecord() {
        super(JDashboard.DASHBOARD);
    }

    /**
     * Create a detached, initialised JDashboardRecord
     */
	public JDashboardRecord(Integer id, String name, String description, Integer projectId, Timestamp creationDate) {
		super(JDashboard.DASHBOARD);

        set(0, id);
        set(1, name);
		set(2, description);
		set(3, projectId);
		set(4, creationDate);
	}
}
