/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.store.jooq.tables.records;


import com.epam.ta.reportportal.store.jooq.enums.JIntegrationAuthFlowEnum;
import com.epam.ta.reportportal.store.jooq.enums.JIntegrationGroupEnum;
import com.epam.ta.reportportal.store.jooq.tables.JIntegrationType;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIntegrationTypeRecord extends UpdatableRecordImpl<JIntegrationTypeRecord> implements Record6<Integer, String, JIntegrationAuthFlowEnum, Timestamp, JIntegrationGroupEnum, Object> {

    private static final long serialVersionUID = 1171090184;

    /**
     * Setter for <code>public.integration_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.integration_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.integration_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.integration_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.integration_type.auth_flow</code>.
     */
    public void setAuthFlow(JIntegrationAuthFlowEnum value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.integration_type.auth_flow</code>.
     */
    public JIntegrationAuthFlowEnum getAuthFlow() {
        return (JIntegrationAuthFlowEnum) get(2);
    }

    /**
     * Setter for <code>public.integration_type.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.integration_type.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.integration_type.group_type</code>.
     */
    public void setGroupType(JIntegrationGroupEnum value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.integration_type.group_type</code>.
     */
    public JIntegrationGroupEnum getGroupType() {
        return (JIntegrationGroupEnum) get(4);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setDetails(Object value) {
        set(5, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getDetails() {
        return get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, JIntegrationAuthFlowEnum, Timestamp, JIntegrationGroupEnum, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, JIntegrationAuthFlowEnum, Timestamp, JIntegrationGroupEnum, Object> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JIntegrationType.INTEGRATION_TYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JIntegrationType.INTEGRATION_TYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JIntegrationAuthFlowEnum> field3() {
        return JIntegrationType.INTEGRATION_TYPE.AUTH_FLOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return JIntegrationType.INTEGRATION_TYPE.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JIntegrationGroupEnum> field5() {
        return JIntegrationType.INTEGRATION_TYPE.GROUP_TYPE;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field6() {
        return JIntegrationType.INTEGRATION_TYPE.DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationAuthFlowEnum component3() {
        return getAuthFlow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationGroupEnum component5() {
        return getGroupType();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object component6() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationAuthFlowEnum value3() {
        return getAuthFlow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationGroupEnum value5() {
        return getGroupType();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object value6() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationTypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationTypeRecord value3(JIntegrationAuthFlowEnum value) {
        setAuthFlow(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationTypeRecord value4(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationTypeRecord value5(JIntegrationGroupEnum value) {
        setGroupType(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public JIntegrationTypeRecord value6(Object value) {
        setDetails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JIntegrationTypeRecord values(Integer value1, String value2, JIntegrationAuthFlowEnum value3, Timestamp value4, JIntegrationGroupEnum value5, Object value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JIntegrationTypeRecord
     */
    public JIntegrationTypeRecord() {
        super(JIntegrationType.INTEGRATION_TYPE);
    }

    /**
     * Create a detached, initialised JIntegrationTypeRecord
     */
    public JIntegrationTypeRecord(Integer id, String name, JIntegrationAuthFlowEnum authFlow, Timestamp creationDate, JIntegrationGroupEnum groupType, Object details) {
        super(JIntegrationType.INTEGRATION_TYPE);

        set(0, id);
        set(1, name);
        set(2, authFlow);
        set(3, creationDate);
        set(4, groupType);
        set(5, details);
    }
}
