name: Build feature Docker image

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'develop'

jobs:
  variables-setup:
    name: Setting variables for docker build
    runs-on: ubuntu-latest
    if: (!startsWith(github.head_ref, 'rc/') || !startsWith(github.head_ref, 'hotfix/') || !startsWith(github.head_ref, 'master') || !startsWith(github.head_ref, 'main'))
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create variables
        id: vars
        run: |
          echo "tag=$(echo ${{ github.head_ref }}-${{ github.run_number }} | tr '/' '-')" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      date: ${{ steps.vars.outputs.date }}
      sha_short: ${{ steps.vars.outputs.sha_short }}

  call-docker-build:
    name: Call feature Docker build
    needs: variables-setup
    uses: reportportal/.github/.github/workflows/build-docker-image.yaml@main
    with:
      aws-region: ${{ vars.AWS_REGION }}
      image-tag: ${{ needs.variables-setup.outputs.tag }}
      version: '${{ github.head_ref }}-${{ needs.variables-setup.outputs.sha_short }}'
      branch: ${{ github.head_ref }}
      date: ${{ needs.variables-setup.outputs.date }}
    secrets: inherit
